### ISSUE TITLE
display of url from bibliography -- doc format html

### ISSUE THREAD

**Issue by schuang** [hplgit/doconce#17] opened 2015-03-11 05:01 UTC
Consider a bibliography item for a web site:
```
@Misc{test,
author = {First Last},
title =  {{T}his title is a test},
url =    {http://test_url.org},
howpublished = {\url{http://test_howpublished}},
year = {2015}
}
```

When building `doconce format pdflatex`, it will displays correctly like this:

![screen shot 2015-03-10 at 9 43 51 pm](https://cloud.githubusercontent.com/assets/451425/6590513/a421e83a-c76e-11e4-8e13-32cac2c6cec7.png)

But when building for `doconce format html`, it generates this:

![screen shot 2015-03-10 at 9 42 58 pm](https://cloud.githubusercontent.com/assets/451425/6590504/7a85a278-c76e-11e4-9ded-de5bc6e0b861.png)

It seems to me that when building `format html`, the HTML code should just display the `howpublished` field (like in `format pdflatex`) or the `url` field, but not both. Or am I doing something wrong?

(Normally url and howpublished would use the same web address. I use different ones here just to see which one is displayed in html and pdflatex, respectively)

The paper.pub file (`publish import mybib.bib`) looks like:
```
$ cat papers.pub 
* misc
** {T}his Title Is a Test
   key:          test
   author:       First Last
   year:         2015
   url:          http://test_url.org
   status:       published
   howpublished: \url{http://test_howpublished}
   entrytype:    misc
```

.do.txt source file:

```
$ cat my.do.txt 
Referece test cite{test}

===== References =====

BIBFILE: papers.pub
```

**Comment by hplgit** [comment] 2015-03-11 16:26
You are absolutely right! The treatment of url vs howpublished was not done consistently (except in latex where it happend to be right because bibtex takes care of those details). The problem is now fixed.

In formats where url/howpublished is less likely (articles, books), the url comes at the very end after year as add-on note. In formats where url/howpublished is likely, such publishing info comes before year (i.e., year appears at the end). This convention looks most natural to me.

Thanks for pointing out this error - it led to clean up of some other smaller details in formatting reference lists.

**Closed by hplgit** 2015-03-11 16:26 UTC

**Comment by schuang** [comment] 2015-03-11 16:43
Thank  you. doconce is an amazing system!
